name: Release

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Releasing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.5.0

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Run type checking
        run: pnpm run typecheck

      - name: Run linting
        run: pnpm run lint

      - name: Create Release Pull Request / Publish Package
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version-packages
          commit: "chore: release package"
          title: "chore: release package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
